[versions]
junit5 = "5.10.1"
log4j = "2.22.0"
log4j-api-kotlin = "1.3.0"
swagger = "1.6.12"
swagger3 = "2.2.19"
javaparser = "3.25.7"

[libraries]
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-slf4j-impl = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j" }
log4j-api-kotlin = { module = "org.apache.logging.log4j:log4j-api-kotlin", version.ref = "log4j-api-kotlin" }


swagger = { module = "io.swagger:swagger-annotations", version.ref = "swagger" }
swagger3 = { module = "io.swagger.core.v3:swagger-annotations", version.ref = "swagger3" }

javaparser = { module = "com.github.javaparser:javaparser-core", version.ref = "javaparser" }

[plugins]
